spring.application.name=Olympic Medal Tracker

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/olympics_db}
spring.datasource.username=${DB_USERNAME:olympics_user}
spring.datasource.password=${DB_PASSWORD:olympics_pass}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# App
server.port=${SERVER_PORT:8080}
api.version=${API_VERSION:api/v2}

# Security
jwt.secret=${JWT_SECRET:OTJiYzRkM2EzNjYxNDNkNjYwOTUwNTM3MTFhZjg0NGYyOTY4ZmZjNTFhOTNiZDk3OTY5MWZiYWE3NTdmYmRiMA==}
jwt.expiration=${JWT_EXPIRATION:3600000}

# Admin bootstrap
app.admin.username=${ADMIN_USERNAME:darth}
app.admin.password=${ADMIN_PASSWORD:vador7}
